travis:
  secure:
    BINSTAR_TOKEN: hZe0hniVnq3n9Pfx0xJsFOjpU949Asi7gSm/Nwl75u7XhapFUDn3TUlfj59siUXapqEO/anL0PwpTW9e8Rm7LxCM80v7LpqCthqZbpr1wt0UDJFmc3xOJWt+tcg+tonk8d2E9bJPLCgIvqBmOiSaDIno8OjI/KiV97xIyEOIlbLhEyvdoy8YL32vg+FGCYEkSQGChONaLSHIg6ce+DgS/BF5TZupY3LNuH8HehtEduqPS5LVRJ+B5guPrNmY5IRydhlr9jWfAoyzttjiQSqTG+eQ8+Ub0st51+Uz4WEKMAbPwAux0v/x/Y24BsisPdrxNsX44BMbPcHKVUFQNC+UzxiR1gyqDb8THo0LxSRGigyAu4r0mWfLWrJ511PLjsOPOwpYnVo6H96pM6ei5/ZyKyLquHIdW2XUNqQY2uXHyQb33bS682txsoffhW70vUnN/2GWupIOaDSej0qwsBhp26h6VCPf7IQkr6W7hnDRMmf+TlB5dRDRN9tehb0OF2EI2Tn3PKZpSXNvCKuKwCN9Hdc6S6uKiPO7NsfSIRub2f4s0+qMoBg7KX2x+7ZP0WYEfz4ZR3MelhxL2ngFFwIKFWqdHYIL7OnjGLdBI73k14FpUt/OPWXo43FHh6UboTPmms9Ay5nqhRxsWWuPmdv2iShneosmfPS146w3hZlo968=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
