travis:
  secure:
    BINSTAR_TOKEN: F9Md/vKCXpQygkIu+oq952gws+xP5x+P6qfs4P4h0iL7uSwvnXibfELK+jD1fSGD8YE0pqmpJaEexbpGIYV3fOMKO1Mx335bs9ENbreA57TpG873FKv883mO0HJwMk2F6nA2EPpVh5IUEtwjFGipbeVTdPPQjlL07TR9MSwKPSv3his68PbmJ/Xd1VTITh7cYWkNuUcVxlgWXiL89qWtoVhHuCMeBib6hlTE/BdW8fp/yhYDCpD2Lic+JvO+6z+JiOF7Sxt2Db7XeET16vjol9VgVI0rg05egmWfMyph0NNF8T+GOcHKxDAaQlyeOyil06bhzqWw7hjoa/5VXQsnfbnuTZKYVsN9q0jJOr/SMMOsLGwBrraGeCVL7PsSZsHAEw4v2lsNHVH9AAeRGaaOlBINnOA80mT0Cv10n2sTRVhyD2tQRQT1LaNt+rUkdKLk5rBjwY/rbuyxZfBhUce/Sd75RRbjwtsftwsY6IP39mm/3iHBxgQo+lOPj3oaYE2ToGQjuYLmjlYjpwlAcJ+VBPRnxFRIaTPNslCfl/Ri7AGF6eyzjmqJILLr97ffCnJS4zGKc9ddM847QwYb+QkmxlYbaAwNEXMPHLDTkjGY3G1gYVklZ0Femq/AhLNIe4jwbNnyCJqyGfotAStMHRci9Cc16+cdDf8aLWRTR8LBTnA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
