travis:
  secure:
    BINSTAR_TOKEN: Nk9JWOeAcYiIUCr69nsgnCYQ8/DCXOt2LrjBfqRpSZwT4BDCff4LNYwP2iq+2l+1SLfXZl5DJAPwj/1WLcfWgkJvAbk0XTKizZ0a0OdJh3x23+E3TyYJ5yQ1UcwXkbiJFXhN42sRqFI2fk3rNuCgkxVHgL/Bd94lOw2Dl0+Z043IVNraAbvDq7/SJGFoeL6bfd/k0MY9Il6PpYCKi4+Ku6Qva4K8vu9bhpQI5h+o/UYZ4nje6768waTTVzneJeNq8HsX09UZlW+C8+pCljVolZU7bwNMpaiuxBNj51H2gnAqFWBxjMm4G69+Rxf6h3Y4C3bl55YY7SHqfhY3WtQFatQAQQWumXLjU6jrF6Cd2a6O6rO+67WMxuw/VvFisvN80BgDdpKQsJ2vkfQvEeKxDqoy+xM8V/+weSU7RmqoIpoi9CrQyZk9ssArQQ7+nu7RonvCDMWfms4SLR7dA+PKmOYde0xUEt+8jKFdxoDGvU5gai9+qDK+IDzaug0/zEVjY5WyT+krFL2z7kf7FDuJrPHFZ4IaPyVNsQD9O0c1LRnCQStg0Pu/HoYXi7Y2caVOa7Yssc1j1jtvloyUDvc690pnIbz5Me657vX9NRs7o3lNLM/ylm5novLn3zsTJI4axDvpc2L8QPH7Ogn5SRs6biJu/tI33jgYFi4vkKx5wNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
