travis:
  secure:
    BINSTAR_TOKEN: NCNR3jQbJNy0ERXhUBagFfvF/Pr28HyRQFQjxikd6cC+wmLnt8+xSq6QhSWZY8cThJAJbIWb8yC4lAbeHGkQ8Xk9cU3e0xNCneac5yVV7vlvUckoAa9tiS8fcjvu+M4kE3Mt5T6nxTOOalDXpJn0zTI3xP+oENckGlbnKtyECiVSQoaVAvetsXkG9e1MdIkpANS3vw2760OCvXyMPCSgKgPEdnxVyMgB1EGFgjuSVq/E/EYrLIuSEDUR2skLHl3DX1niLy1vQnYVzx2PtW7wxbPZAn1ryZyyb54cu3c4Jc3L2eZg5MKPsmDk2E71AEJeXHzdFJULpjwGyYs3m8HuPSFNDgcbPXmUEeLs66oUOu+0yQFX3VkJRAi6WRFgzUDzihOggKsSm2DpzpGauUtYcqODn7Kl5pU6qYxlORMicaOnac+BdCtjH8uqhl+HgwNVaEvgyFnWeVT9EmkKccwMeuGjTx7xMDciIPnWQLAgQVQ/CLontA9MyQOCd38LF7W8xATm/rbF9FbVM/+fGWZiX3VCU0EVa16p/BZkzKd7D20zdPhqMb8t2XlNOGFZURoCgUTEmw7K1MAcSMtP6zV1CR0kEToB/d7NIh5DjNQSTx1kjQ0WNzRezhjaThE2jXL/ay6eG3G4I8/dCqvpjXtMTGEU3PGRBIRycL/oMyGV9Bk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
