travis:
  secure:
    BINSTAR_TOKEN: ZSEGBnhZzoAEMtWLNzMJk3huN2Ps1WxFaT35wUkt6vHJurZR+z+EZ1xGTzlPr35NHir//mIXf/2vS94LwHXXEy16MZ98fovOuY54ms5bSKPQChHBSXITuiHhikk6Rf8JwSROumZTIOf4qYkNTAVrEZDyNAUCSuoj0BwiMn5KEBMIklc/8g2ZVpqejya65wr2cnjfb7f5nu+wmBGhjrhEefMmSFTABJ/FHNmRO+c18JbnMx99qOCWy3bXN/HKxT9kTvJufdHrzHBmhwZDO7du4uvv+mBnX25Ne7xnwG/6TrrxVDA7GgyzPJ2W+rI6Gly3nrmipsG+ce3QFIzBIHqnFWuX4dnWPprL1LrZy/nBbtfhuM2i1pjknOHok2BLm3ruO7PLG1viw/fT1rMQPzi4EB2+OB9PVE/w5WWlt4Ju2ImQx98JY8Q66IFAVPkBMq+9OMNIQPgi8JGguYO+eSwothgSqhnq0IPDXOYU4co9q83vvo1F/2lVbAmpbLAGUfM/M6w9oP35bAda4SuRE930Fl3T3USUe81Z0M3asFXLp8E+krxxYaztpN8C2VrQJ4gHzXCC/+D72adlyb1kbn2rdXZWTFfOmn0XrwCXfTO5feHbZwdWOjHNyOymbYmLSe5sByx1lQX9fcI6JKcXjfvClOD371QnS6LCUyMSzD7lX5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
